import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './About.scss';
import ProfileImg from '../../assets/images/profile.jpeg';
import Button from '@mui/material/Button';
import { useNavigate } from 'react-router-dom';
import { useAuthValue } from '../../context/AuthContext';
const About = () => {
    const navigate = useNavigate();
    const { user } = useAuthValue();
    const handleRedirect = () => {
        navigate('/posts/create');
    };
    return (_jsxs("div", { className: "About", children: [_jsxs("div", { className: "container", children: [_jsxs("main", { children: [_jsxs("h1", { children: ["About My", _jsx("span", { className: "posts-title", children: "Posts" })] }), _jsxs("p", { children: ["This project was developed by ", _jsx("a", { href: "https://vertocode.com", children: "vertocode" }), ", leveraging React for the frontend and Firebase for the backend."] }), _jsx("p", { children: "The primary objective of this project is to provide a platform where individuals can easily create and share blog posts. Unlike conventional websites, MyPosts emphasizes a streamlined approach to showcasing profiles through a simple list of posts." }), _jsx("p", { children: "Personally, as a developer, I initially created my own blog using custom code. However, I questioned, \"Should one need to be a programmer to have a blog?\" This pondering led to the inception of MyPosts, aiming to simplify the process for everyone." }), _jsx("p", { children: "With MyPosts, anyone can effortlessly create and share posts with recruiters, colleagues, and friends. While there are other platforms for socializing, MyPosts stands out with its exclusive focus on posts!" }), _jsx("p", { children: "If you have any constructive feedback, please feel free to reach out! You can contact me via email or LinkedIn." }), _jsx("p", { children: "Thank you for taking the time to read about MyPosts!" })] }), _jsxs("aside", { className: "profile-image-container", children: [_jsx("img", { src: ProfileImg, alt: "profile.jpeg" }), _jsx("h3", { children: "Everton Vanoni" }), _jsxs("h4", { children: ["Creator of My", _jsx("span", { className: "posts-about", children: "Posts" }), " "] }), _jsxs("div", { className: "social-media", children: [_jsx("a", { href: "https://www.linkedin.com/in/evertonvanoni/", target: "_blank", rel: "noreferrer", children: _jsx("i", { className: "fab fa-linkedin" }) }), _jsx("a", { href: "mailto:evertonvanoni@gmail.com", target: "_blank", rel: "noreferrer", children: _jsx("i", { className: "fa fa-envelope" }) }), _jsx("a", { href: "https://vertocode.com", target: "_blank", rel: "noreferrer", children: _jsx("i", { className: "fa fa-blog" }) }), _jsx("a", { href: "https://github.com/vertocode", target: "_blank", rel: "noreferrer", children: _jsx("i", { className: "fa fa-github" }) }), _jsx("a", { href: "https://gitlab.com/vertocode", target: "_blank", rel: "noreferrer", children: _jsx("i", { className: "fa fa-gitlab" }) })] })] })] }), user && (_jsxs("footer", { children: [_jsx("h2", { children: "Start build a new post to share with friends \u2013 I bet they'll like it!" }), _jsx(Button, { onClick: handleRedirect, variant: "contained", color: "primary", children: "New Post" })] }))] }));
};
export default About;
